---
- hosts: localhost
  become: true
  tasks:
  - name: install i3 
    community.general.pacman:
      name:
      - i3-gaps
      - i3status
      - i3lock 
      state: latest

  - name: install discord 
    community.general.pacman:
      name: discord 
      state: latest
