
- hosts: localhost
  become: true
  tasks:


  - name: install pacman unorganized software
    community.general.pacman:
      name:
        - kitty
        - tmate
        - chromium
        - lazygit
        - evince
        - pandoc
        - transmission-gtk
        - fish

      state: latest

  - name: install tmate
    community.general.pacman:
      name: tmate
      state: latest

  - name: install doom pre-requisites
    community.general.pacman:
      name:
        - emacs-nativecomp
        - ripgrep
        - fd
        - python-markdown
        - shellcheck
        - cmake
      state: latest
 
  - name: install python packages
    community.general.pacman:
      name:
        - python
        - python-pip
      state: latest


  - name: Create the `aur_builder` user
    become: yes
    ansible.builtin.user:
      name: aur_builder
      create_home: yes
      group: wheel

  - name: Allow the `aur_builder` user to run `sudo pacman` without a password
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'

  - name: install rcm
    kewlfft.aur.aur:
      use: yay
      name: rcm
    become_user: aur_builder

  - name: install aur communication tools
    kewlfft.aur.aur:
      use: yay
      name:
        - zoom
        - teams
        - hexchat
    become_user: aur_builder

  - name: install aur needs to be cleaned
    kewlfft.aur.aur:
      use: yay
      name:
        - zotero-bin
        - brscan4
        - flameshot
    become_user: aur_builder

  - name: install doom pre-requirements
    kewlfft.aur.aur:
      use: yay
      name:
        - discord
        - signal-desktop
        - zoom
        - visual-studio-code-bin
        - google-chrome
        - slack-desktop
    become_user: aur_builder
